package pl.exsio.nestedj.config.mem.identity;

import java.io.Serializable;

/**
 * Identity generator used for inserting new Nodes into an InMemory Repository.
 * If you want to have an interoperability between InMemory implementation and DB-based implementation, make sure that
 * IDs generated by implementation of ths interface are compatible with your database configuration.
 *
 * @param <ID> - Nested Node ID Class
 */
public interface InMemoryNestedNodeIdentityGenerator<ID extends Serializable> {

    /**
     * Generates a unique identity for InMemory repository Node insertion
     *
     * @return ID - newly generated unique identity
     */
    ID generateIdentity();
}
